### ISSUE TITLE
Payed invoice in MB on hold

### ISSUE THREAD

**Issue by marvin0o** [sensson/whmcs-moneybird#10]
Hi

I've installed the module with succes. The sync works with contact and invoices. 

Test 1: When I make an test invoice with no payment it sync to Moneybird with status Processing.  Thats ok. 
When set the invoice in WHMCS manually to paid, the invoice in Moneybird still remain processing?

Test 2: When make a new order in the backend of WHMCS and put it right away to status paid, 
the invoice still sync to Moneybird as processing. 

Best case for me would be:
Processing orders in WHMCS not to sync.
Only sync Paid order from WHMCS with the status Paid in Moneybird to.

**Comment by marvin0o** [comment]
Hi Thanks for your reply.  I only want to use moneybird sync to get the PAID invoices from WHMCS to Moneybird for my administration. Want them to pay with WHMCS. 

Only paid orders to MoneyB. You said remove line 47 good tip. But the status in Moneybird is still processing while the order is paid in WHMCS.

- Possible that paid orders sync to MB get on paid state instead processing.
- Also possible to sync order to MoneyB it get marked as " Invoice manual send" . MB don't need to send it to customers automatically. WHMCS will handle that.

Then it will be working perfectly for me. I can donate you some fee for your help!

**Comment by ju5t** [comment]
What you propose is not a sustainable solution. Your ledgers will never match up. Removing line 47 is a workaround, but we have no intention to make it work like that and neither do we take on paid jobs, sorry. If you want this functionality you either have to hire an external developer make this for you or make the changes yourself.

MoneyBird isn't sending invoices to your customer if you use this module. See [Invoice.php#L212](https://github.com/sensson/whmcs-moneybird/blob/master/lib/Models/Invoice.php#L212).
