### ISSUE TITLE
Payment (Mutation) Cron Error 

### ISSUE THREAD

**Issue by HugotonHosting** [sensson/whmcs-moneybird#11]
Hello,

  We have set up the WHMCS integration but receive the below error on cron.php - no payments/mutations are moved from WHMCS to Moneybird.  Please can you assist?

[WHMCS Application] ERROR: TypeError: Argument 1 passed to Picqer\Financials\Moneybird\Entities\FinancialMutation::getVersions() must be of the type array, null given, called in hugotonhosting.co.uk/public_html/members/modules/addons/moneybird/cron.php on line 131 and defined in hugotonhosting.co.uk/public_html/members/modules/addons/moneybird/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Actions/Synchronizable.php:43 Stack trace: #0 hugotonhosting.co.uk/public_html/members/modules/addons/moneybird/cron.php(131): Picqer\Financials\Moneybird\Entities\FinancialMutation->getVersions(NULL) #1 hugotonhosting.co.uk/public_html/members/modules/addons/moneybird/cron.php(214): processFinancialMutations(Array, true) #2 {main} {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Picqer\\Financials\\Moneybird\\Entities\\FinancialMutation::getVersions() must be of the type array, null given, called in hugotonhosting.co.uk/public_html/members/modules/addons/moneybird/cron.php on line 131 at hugotonhosting.co.uk/public_html/members/modules/addons/moneybird/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Actions/Synchronizable.php:43)"} []

**Comment by ju5t** [comment]
It works the other way round. It uses MoneyBird as a single source of truth for financial mutations. It will not sync payments from WHMCS into MoneyBird. You won't be able to get your ledgers synced if you would.

I think this can happen if you have no mutations in MoneyBird yet. Can you confirm this?

**Comment by HugotonHosting** [comment]
Ah okay, thanks for confirming.  I added a test mitation in Moneybird and the error went away.

We won't be using Moneybird though unfortunately as we cannot import our PayPal transactions in automatically.

Thanks for your help!

**Comment by ju5t** [comment]
PayPal support would have been a good feature for us too. You could raise a feature request but they often take time, unfortunately.

I will leave this issue open as we could make this behaviour more obvious. Thanks for raising this issue!

**Comment by ju5t** [comment]
This has been solved by PR #12.
