### ISSUE TITLE
Installation steps are insufficient

### ISSUE THREAD

**Issue by twelvetrains** [sensson/whmcs-moneybird#14]
Referencing a previous issue (see below):

Also for me, there is simply not enough information as to exactly how the installation should be done. When I run 'composer install' in SSH on the server, I get the following error:

"Composer could not find a composer.json file in /home/twelve1q"

When i run 'composer install /home/twelve1q/public_html/accounts/modules/addons/moneybird' I also get an error. 

Could the installation information please be updated with the exact instructions? I would really appreciate that. :-)

WHMCS is updated to the most recent stable version: 7.9.1

—

@biwd you have to run `composer install` as the README says. You can't leave out one of the installation steps.

See: https://github.com/sensson/whmcs-moneybird#installation

_Originally posted by @ju5t in https://github.com/sensson/whmcs-moneybird/issues/8#issuecomment-527193840_

**Comment by ju5t** [comment]
Which error do you get when you run the composer command in `modules/addons/moneybird`?

You should get:

```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 5 installs, 0 updates, 0 removals
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)
  - Installing psr/http-message (1.0.1): Downloading (100%)
  - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)
  - Installing guzzlehttp/guzzle (6.3.3): Downloading (100%)
  - Installing picqer/moneybird-php-client (v0.18.3): Downloading (100%)
guzzlehttp/guzzle suggests installing psr/log (Required for using the Log middleware)
Generating autoload files
```

The exact steps were:

```
$ git clone git@github.com:sensson/whmcs-moneybird.git
$ cd whmcs-moneybird
$ composer install
```

I have chosen to do a `git clone` but the end result if you download the zip-file from this repo isn't any different. If you upload all files including the `vendor` folder that composer has generated for you, it should 'just' work. 

The only thing I can think of is an error with composer. Either because it's not installed or because of a dependency thing with PHP and/or the composer packages we require.

**Comment by twelvetrains** [comment]
Thanks for your quick reply! With your tips, I managed to get it done by doing the following in this order:

```
Upload all files to modules/addons/moneybird/ with FTP
$ cd /home/[accountname]/public_html/accounts/modules/addons/moneybird
$ composer install
```

The path is of course different for each install. Cheers!

**Comment by twelvetrains** [comment]
I'm back with the next issue. In the readme.md file the next step is to setup the module. I think I have managed to do that, because at the MoneyBird API token it says that there is 1 active connection.

But the next steps, Ledger and tax mapping, I encountered an issue. I can not find find 'Addons > Moneybird > Tax mapping' nor 'Addons > Moneybird > Ledger mapping'. See screenshot below.

So where can I find the Ledger and Tax mapping? Thanks.

<img width="1008" alt="Schermafbeelding 2020-02-04 om 14 56 53" src="https://user-images.githubusercontent.com/13319952/73751124-b9ec7200-475e-11ea-96f9-4b9338a570bc.png">

**Comment by ju5t** [comment]
This isn't a theme I have seen before. Apparently they haven't included all features WHMCS supports. They should be on the left hand side when you use the default theme.

**Comment by twelvetrains** [comment]
Alright, thanks. I guess I'll have to switch to the default theme to set it up and then switch back after that. Thanks!

**Comment by ju5t** [comment]
Cool. Not too sure what we should change in our documentation though. Your steps are essentially the same as we've got documented, but instead of running `composer install` on your local machine, you ran it on the remote server.

**Comment by twelvetrains** [comment]
I'm a WordPress developer and I write instructions for my clients. The exact steps AND the correct order of the steps is important. In your instructions step 1 is: 'Run composer install'. That didn't work. When I did that als the last step, it worked. And your instructions do not mention anything about a remote machine. ;-)

**Comment by twelvetrains** [comment]
NEXT ISSUE: The cron job does not seem to be working. I have set up everything as it should according to your instructions, also the 'Enable cronjob' in the settings is turned on. But no invoices are synced to MoneyBird. 

Any suggestions? Thanks. :)

**Comment by ju5t** [comment]
I don't think you can compare WordPress users to developers on GitHub.

> And your instructions do not mention anything about a remote and/or local machine

That's because it doesn't matter where you run `composer install`. It can be a server, a local machine or even a Docker container during your CI/CD builds. Whatever suits your workflow. 

I don't know why `composer install` didn't work for you at first. The only reason I can think of is a mismatch between one of the dependencies in `composer.json` and PHP on your local machine. 

Have you tried running the cron on the command line of the server WHMCS is running on? What does it say when you do? Do you see any error messages?

**Comment by twelvetrains** [comment]
What I meant was that I have a lot of experience with writing clear instructions, not for WordPress. ;-)

I tried earlier to run 'composer install' on my local machine and that didn't work.

I get the following messages when I run the cron on the command line:

public_html/accounts/modules/addons/moneybird/cron.php: regel 1: ?php: Bestand of map bestaat niet
public_html/accounts/modules/addons/moneybird/cron.php: regel 3: //: Is een map
public_html/accounts/modules/addons/moneybird/cron.php: regel 4: require_once: opdracht niet gevonden
public_html/accounts/modules/addons/moneybird/cron.php: regel 5: require_once: opdracht niet gevonden
public_html/accounts/modules/addons/moneybird/cron.php: regel 6: require_once: opdracht niet gevonden
public_html/accounts/modules/addons/moneybird/cron.php: regel 7: require_once: opdracht niet gevonden
public_html/accounts/modules/addons/moneybird/cron.php: regel 9: use: opdracht niet gevonden
public_html/accounts/modules/addons/moneybird/cron.php: regel 10: use: opdracht niet gevonden
public_html/accounts/modules/addons/moneybird/cron.php: regel 11: use: opdracht niet gevonden
public_html/accounts/modules/addons/moneybird/cron.php: regel 13: //: Is een map
public_html/accounts/modules/addons/moneybird/cron.php: regel 14: syntaxfout nabij onverwacht symbool '!='
public_html/accounts/modules/addons/moneybird/cron.php: regel 14: `if (php_sapi_name() != "cli") {'

**Comment by ju5t** [comment]
Can you share the exact command that you use to run the cronjob?

**Comment by twelvetrains** [comment]
I didn't really run a command, as I couldn't find how to do that anywhere, except just the path to the cron.php file, which is:

public_html/accounts/modules/addons/moneybird/cron.php

**Comment by twelvetrains** [comment]
I looked a little further and found that this worked:

$ php -f public_html/accounts/modules/addons/moneybird/cron.php

It imported 10 invoices. So the cron is working. But the automatic cron is not working.

**Comment by ju5t** [comment]
If the cron is working on the CLI there is no reason why it shouldn't work as a cronjob. I'm sorry but you would have to take this up with your sysadmin to find out why the cron isn't working for you.

**Comment by twelvetrains** [comment]
Alright. Then the next issue:

Some of the imported invoices have been marked as payed in WHMCS with a transaction. This is not reflected back in MoneyBird. Is this an issue or how does this work. 

Thanks.

**Comment by ju5t** [comment]
It uses Moneybird as a single source of truth for your financial mutations. It will not sync payments from WHMCS into Moneybird. You won't be able to get your ledgers in sync if it would.

You can only have one source of truth when it comes to accounting.

**Comment by twelvetrains** [comment]
In my case WHMCS handels almost all payments automatically so it's going to be a waste of time for me to add payments by hand in MoneyBird.

Anyway, I'm 'only' going to use MoneyBird handle bookkeeping more easily. :-) 

Thanks for your help in this, I appreciate it!

**Comment by ju5t** [comment]
No problem.

Keep in mind that WHMCS isn't following any accounting principles and their practices are often illegal in the EU. I wouldn't use this integration if you're not going all in with Moneybird.

I suggest to speak to an accountant about it. 

Either way, I'm going to close this issue.
