### ISSUE TITLE
Create invoice loop

### ISSUE THREAD

**Issue by ikbenjoeri** [sensson/whmcs-moneybird#15]
Every time the cronjob is running, the same invoice is created again in moneybird

https://i.imgur.com/TFBQm5o.png

**Comment by ju5t** [comment]
For some reason the `sendInvoice()` method is not called in lib/Models/Invoice.php#L212.

https://github.com/sensson/whmcs-moneybird/blob/9c6b22194b289c58e9641c3416dcb4f2dc93861d/lib/Models/Invoice.php#L212

My first guess would be that you did not set up any of the ledgers. 

The module logs exceptions in mod_moneybird_log. This table is created during the installation and at the moment it is only accessible if you access the database directly. If there is an entry there, could you share it?

What is the output of the cron when you run it by yourself?
