### ISSUE TITLE
Moneybird asks for Callback URL

### ISSUE THREAD

**Issue by defcon8** [sensson/whmcs-moneybird#18]
Hi there,

Great work, looking forward to use your plugin. But when I try to create an API token at Moneybird, I have to fill in a callback URL.

<img width="1107" alt="Schermafbeelding 2021-07-24 om 18 14 31" src="https://user-images.githubusercontent.com/3636349/126874684-86752148-73f0-45da-944e-5f88bd566920.png">

So what should I enter here?

Kind regards,

Bastiaan

**Comment by ju5t** [comment]
None, it should be for personal use. We're not using the OAuth protocol. If that doesn't work, let me know.

**Comment by defcon8** [comment]
I see! Thanks!

**Comment by defcon8** [comment]
@ju5t: Works like a charm! Case closed. Is there a way to donate a beer or coffee for this great piece of work? :)

**Comment by ju5t** [comment]
@defcon8 cool! No need to donate a beer or coffee, I'm happy that you find useful!
