### ISSUE TITLE
Upload via FTP (possibly without using composer?)

### ISSUE THREAD

**Issue by nickvdmee** [sensson/whmcs-moneybird#19]
Hi there,

We tried uploading the module through FTP but it does not show in WHMCS.
We also tried running it with composer but no luck either.
I am guessing we're doing something wrong but since we we're able to succesfully upload/install several other modules/addons and gateways we can't figure out what it is.

**Is it possible to get the module/files without the need to run composer?**
We saw an issue about this from 2019, but those files do not seem to fix it for us as well.

Thank you in advance.

**Comment by ju5t** [comment]
@nickvdmee you cannot use this module without composer.

The easiest solution is to download the module on your own machine, change into that directory and run `composer install` there. When this is finished, you should see a `vendor` folder.

You can then upload everything to `modules/addons/moneybird/`.

This should should work. If not, please share any error messages here, without errors it's pretty hard to help out.

**Comment by nickvdmee** [comment]
sorry dont get it, we download the files, unzip them and then what? how do we run composer install here? dont see that option?

**Comment by nickvdmee** [comment]
Ok so we have done the above, we see a vendor folder now but when we upload everything we do not see it in WHMCS
![Schermopname (758)](https://user-images.githubusercontent.com/25768785/143870498-73f1183b-f133-4958-bde4-48fe15c4805f.png)
![Schermopname (759)](https://user-images.githubusercontent.com/25768785/143870501-3b5f5c74-1aeb-4128-8257-fd50d1ce886a.png)

See folders in screenshots, (removed from installation so see left side of Filezilla) if we upload these nothing is visible in WHMCS. 

What more needs to be done?

**Comment by ju5t** [comment]
@nickvdmee you have to create a folder called `moneybird` in the addons folder. You then upload all the contents of what is called `whmcs-moneybird-main` on your local machine. If you do this it should work. If not, please be more specific about what you mean by that you're not seeing it in WHMCS.

**Comment by nickvdmee** [comment]
exactly that, i did not see it. Sorry but it was/seems very confusing, with other addons you just upload and configure, no need for composer or create/name folders yourself.
Also the readme literally reads: * Upload all files to `modules/addons/moneybird/`. NOT create a folder named moneybird..

So that is why it did not work, we got it now, thank you.

**Comment by nickvdmee** [comment]
Sorry cant find other things as well, it also reads: We strongly recommend to map your taxes in WHMCS to your tax rates in
Moneybird. This is done via Addons > Moneybird > Tax mapping. 


Don't see Tax mapping, not in the folders/directories via FTP or in the settings (see screenshot)
What are we doing wrong?
![Schermopname (761)](https://user-images.githubusercontent.com/25768785/143929525-22cd8178-fe66-4bf9-8cd1-84aa483e0676.png)

The same is true for: This is done
via Addons > Moneybird > Ledger mapping. 

Don't see that anywhere as well.

**Comment by ju5t** [comment]
@nickvdmee not sure how to make this more clear. It's basically: go to Addons (in the top menu) > Click on Moneybird > Click on Ledger mapping. This last link is on the left side. This is standard practise for WHMCS modules.

> Also the readme literally reads: * Upload all files to modules/addons/moneybird/. NOT create a folder named moneybird..

It kind of implies that you have to create it if it's not there.

If you feel any of the documentation is lacking details, feel free to PR a change. Keep in mind that though that this module isn't meant to be plug & play like other modules. You need some basic understanding of Composer and WHMCS for it to work. You also need to know some basics on accounting, ledgers and tax.

This generally isn't something we feel needs more in depth documentation, but it could be something obvious is missing.

**Comment by nickvdmee** [comment]
Hi there, sorry but neither do i, i will try with images: top menu, setttings (there is no option addons here as can be seen):
![Schermopname (767)](https://user-images.githubusercontent.com/25768785/144210923-696499f2-b0b7-4bb1-a77d-1833f609c373.png)

Click on modules/add-ons (the only option in the system that leads to Moneybird:
![Schermopname (769)](https://user-images.githubusercontent.com/25768785/144211227-726da4cf-7d03-4435-8b19-bd671e81bf2c.png)

And then you see:

![Schermopname (761)](https://user-images.githubusercontent.com/25768785/144211294-1284cb0a-9bdc-401d-8d93-10f2b4e3b290.png)

So what are we missing? We really do not see any option to ledger mapping, nor tax mapping (besides the allready standard "tax configuration" in the left sidebar).

Thanx again for helping out.
