### ISSUE TITLE
@nickvdmee this is going to sound very unfriendly, but if you want to use this module we do expect some sort of basic understanding of WHMCS.

### ISSUE THREAD

**Issue by nickvdmee** [sensson/whmcs-moneybird#20]
HAHAHA... no problem with getting the other modules to work.. so even it is our own blindness/mistake there is absolutly no reason to be this harsh and unfriendly... really in dealing with over 500 businesses/companies/people in the past 5 years never ever had i had such a poor and unfriendly reaction... not even talking about the fact that people makes mistakes... so again even if it is my "lack of knowledge" there is no reason to act like this and just close the topic... what we might lack in knowledge for this system (for now), you most certainly lack in decency/kindness... have a nice day! 

@nickvdmee this is going to sound very unfriendly, but if you want to use this module we do expect some sort of basic understanding of WHMCS.

Almost every single module in WHMCS is accessible via Modules. It's in the blue bar on the right. You don't go into settings. Most modules only have some basic information. Advanced configuration needs to go elsewhere, it's just how WHMCS works.

If you're not familiar with WHMCS, sorry, but this module isn't for you, nor can we support you in the future.

edit: I'm closing this issue. This is not a problem with the module.

_Originally posted by @ju5t in https://github.com/sensson/whmcs-moneybird/issues/19#issuecomment-983599157_

**Comment by ju5t** [comment]
@nickvdmee make of it what you will. 

This module is completely open source and available for free so everyone can benefit from the time and effort we have put into this. We do this with a lot of hosting related software or technology as it helps others. It's not feasible for us to help everyone in as much detail as you have asked from us. As we give support on this product for free, out in the open, so others can learn from it too. 

In return, if you want to use this module, we expect that its users have enough understanding of WHMCS and put a fair amount of time in it themselves too; and if something is 100% unclear in our documentation, we're open to a pull request that improves this module.

I fully understand that not everyone has the same amount of experience with WHMCS, Composer or other requirements of this module, but in the case, this module might not be for you. This isn't just for this module; it's for pretty much all the software that people make and give out for free.

My comment wasn't meant to offend you; but this module just isn't 100% plug & play. As such, if you're not that experienced with WHMCS yet or with Composer, it can be a bit more difficult. I did help you with all of your questions; but you're last comment triggered me: this really is something that you could have checked better before posting here. If you think about, I'm sure you'd think the same. In the end; I did give you the answer to your question though.

If you want this to be more plug & play, feel free to help. PR's are open to everyone so if you think the documentation needs to improve, you can. If you don't want to play, fair enough, you can still use this module.

**Comment by ju5t** [comment]
@nickvdmee one thing I'd like to add here: I've updated the README to include that you should create the folder if it doesn't exist. I also explained our reasoning for using Composer and have provided an alternative for people without it. This is not 100% finished, thats why #21 is opened.

I can't promise when that will be done though.

**Comment by nickvdmee** [comment]
Thank you very much for this update. We managed to get it to work, apparently the settings in modules/addons need to be ticked (the tickboxes), we we're informed that when none we're ticked it would show in all cases (administrator, sales operator, support operator) but this was false, ticking them made it show where you mentioned and from there on it was easy to configure the remaining tasks.
Have a nice day.

**Comment by ju5t** [comment]
@nickvdmee got it. If you think this should be improved in the documentation of this module feel free to open a pull request that changes the documentation. Personally, I don't think so, but having to enable an add-on for administrators in WHMCS is something I have never understood either, so it might make sense to emphasise that.

**Comment by nickvdmee** [comment]
Thank you for mentioning that but i agree with you, you should not have to mention that in the documentation.
I personally think its something that should be either automatically done/set (at least for admins) or be more clear in WHMCS documentation.
