### ISSUE TITLE
Install package is missing a 'vendor' folder

### ISSUE THREAD

**Issue by twelvetrains** [sensson/whmcs-moneybird#22]
After installing the whmcs-moneybird module the following error occurs in WHMCS:

—
Fatal error: require(): Failed opening required '/home/twelve1q/public_html/accounts/modules/addons/moneybird/vendor/autoload.php' (include_path='.:/opt/alt/php73/usr/share/pear') in /home/twelve1q/public_html/accounts/modules/addons/moneybird/moneybird.php on line 22
—

Composer version 1.8.4 is running on the server. 

When checking the installation files there is no 'vendor' folder. Am I missing something? And with composer version should be used with this module?

Thanks.

**Comment by ju5t** [comment]
The module has no preference when it comes to Composer but personally I would suggest moving onto version 2 as it's the latest stable version out there.

Can you perhaps give a bit more detail? What steps have you taken so far that got you to this point? Did you use the version from Github or did you use the pre-packaged version (which I just found does not include the vendor folder as it should, so this needs be fixed).

In #14 you had the same issue. Could you explain what changed in the meantime?

**Comment by twelvetrains** [comment]
Hi, and thanks for your reply. In the installation instructions Composer is mentioned as required:

https://github.com/sensson/whmcs-moneybird

See the instructions further below.

**Comment by twelvetrains** [comment]
Regarding your question "In #14 you had the same issue":

That was with a previous version of WHMCS and of the Moneybird module. And to be honest, I had forgotten about that. And I see now my own instructions in that thread, which work for cPanel:

https://github.com/sensson/whmcs-moneybird/issues/14#issuecomment-581910686

I have now followed those instructions now and that worked! 

What a pity that you haven't updated the instructions to include my suggestions. :-(

But thanks for reminding me about the same issue back then.

**Comment by twelvetrains** [comment]
It did work, except the 'Workflow Mapping' button in the Moneybird settings and throws an error. See screenshot:

https://www.dropbox.com/s/ltbny8hheuquq6i/workflow_mapping%20error.png?dl=0

**Comment by twelvetrains** [comment]
I really appreciate that this is an open source project. Though I did assume that Moneybird is supporting the project financially, but maybe that is not so? I've now created a fork with a change suggestion to the README.md file. :)

The automatic update messed up my WHMCS installation so I had to update manually. This has happend before and it's always a hassle to get everything working again, as the Moneybird module. I've had to upload and reconfigure several modules I use. 

> Hm, I'm not sure what happens there. Which version of WHMCS are you using right now? Does this happen when you submit a form or when you just view the workflow mapping page? Can you also share if you have enabled some payment gateways as from what you said this seems a new WHMCS installation?

I installed the latest stable version 8.3.2 of WHMCS. It happens when I want to view the workflow mapping page, so just when clicking the workflow mapping link. I have enabled the same payment gateways as before the update: Cash and a few Mollie payment options.

Thanks for your time, I appreciate it!

**Comment by ju5t** [comment]
Moneybird is not supporting this in any shape or form. In fact, because it's an open source project without a formal support structure, they didn't want to include it in their documentation, where other paid solutions are advertised. In a way you could say it's paid for by Sensson, although we just share what we use ourselves.

ps. in your fork, you need to open a PR (Pull Request). I think it points you to that automatically? If not, [about pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) is probably a good starting point.

> I installed the latest stable version 8.3.2 of WHMCS. It happens when I want to view the workflow mapping page, so just when clicking the workflow mapping link. I have enabled the same payment gateways as before the update: Cash and a few Mollie payment options.

Ok, not yet sure what causes this yet but it helps. I will try to spend some time on it tomorrow to see if I can the problem. We're a few versions behind so it might be something has changed. Are all other pages working fine? E.g. the ledgers? And is it loading all Moneybird data there as you'd expect?

**Comment by twelvetrains** [comment]
Sorry for my late reply. Quite an odd choice of Moneybird. 

I created a pull request which you must now be able accept or deny. 

The importing of the invoices is working, so that does now work as expected. Yes, all other pages like the legers are working fine. So for me we can leave it as is for now. 

Thanks again for your time!
