### ISSUE TITLE
Prices VAT

### ISSUE THREAD

**Issue by LaggedHosting** [sensson/whmcs-moneybird#25]
Hi,

I've got my prices in WHMCS as VAT included.
But, after setting it all up, after it exports it to WHMCS, Moneybird still ads the VAT to the bill.
This means my income is higher then it actually is.

Is this because the addon can't deal with VAT included, or a setting in Moneybird (That i cant find)

**Comment by ju5t** [comment]
Prices including VAT are unsupported. See https://github.com/sensson/whmcs-moneybird/issues/13#issuecomment-579116630 for more detail.

I would strongly advise to use prices excl. VAT in WHMCS. It makes everything a lot easier. Especially VAT itself.

**Comment by LaggedHosting** [comment]
Already found it, its not an option you need to change in your module, but Moneybird itself can do it for you.

And for consumers, prices icl. vat is allot nicer to them.

**Comment by ju5t** [comment]
What did you change in Moneybird? If there is a workaround for it that might help others too.

**Comment by LaggedHosting** [comment]
You go to your Administration Settings > Workflows > Your default workflow for the module, Then there is Prices are:

Changed that from Including VAT, that fixed it.

Took me a good 3 hours to find, was not expecting it there.

**Comment by ju5t** [comment]
@LaggedHosting I wouldn't have known that either. Pretty cool that it works though!
