### ISSUE TITLE
Not importing invoices to Moneybird

### ISSUE THREAD

**Issue by ELAXXL** [sensson/whmcs-moneybird#32]
Hi there,

We have been using this plugin for over a year now but sadly since a week the invoices in WHMCS are not being made in Moneybird anymore, any idea how we can solve this?
Do you need any log from us, and if so where can we find this?
Thank you in advance.

**Comment by ju5t** [comment]
The easiest way to see what's going wrong is to run the cron by hand. That should give you an idea of where it might go wrong. If you see the output, I imagine you might already know what to look for on your end. Besides, it's always a good idea to check if there have been any changes in your installation.

I will close the issue for now. But if you cannot fix it with the output of the cron, please tag me here, and we'll go from there.

**Comment by ju5t** [comment]
How did you create this log? Is this what you get if you run the cron? Have you changed the code somewhere? This doesn't look like output we would create from the plugin.

If you made changes yourself, please share them, as it's incredibly difficult to help you otherwise.
