### ISSUE TITLE
Guzzle/Http calls fail in WHMCS

### ISSUE THREAD

**Issue by ju5t** [sensson/whmcs-moneybird#5]
`picqer/moneybird-php-client` requires Guzzle 6 or higher. WHMCS includes version 5. As WHMCS includes third party modules in its update process it fails because it suddenly uses Guzzle version 6 instead of 5. Some of the parameters WHMCS passes to Guzzle are invalid in version 6.

Unfortunately, this breaks the update mechanism in WHMCS.

**Comment by vertizio** [comment]
Confirmed. Not able to use the addon. 

Getting this error: 

[WHMCS Application] ERROR: GuzzleHttp\Exception\ClientException: Client error: `GET https://moneybird.com/api/v2/999999999999999999/financial_mutations/synchronization.json?filter=period%3A201906..201907%2Cmutation_type%3Adebit` resulted in a `401 Unauthorized` response: {"error":"No access to bank"} in /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) #3 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #4 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true) #5 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn() #6 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending() #7 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList() #8 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() #9 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/guzzlehttp/guzzle/src/Client.php(106): GuzzleHttp\Promise\Promise->wait() #10 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Connection.php(217): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request)) #11 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Actions/Synchronizable.php(32): Picqer\Financials\Moneybird\Connection->get('financial_mutat...', Array) #12 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/cron.php(119): Picqer\Financials\Moneybird\Entities\FinancialMutation->listVersions(Array) #13 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/cron.php(214): processFinancialMutations(Array, true) #14 {main} Next Picqer\Financials\Moneybird\Exceptions\ApiException: Error 401: {"error":"No access to bank"} in /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Connection.php:496 Stack trace: #0 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Connection.php(229): Picqer\Financials\Moneybird\Connection->parseExceptionForErrorMessages(Object(GuzzleHttp\Exception\ClientException)) #1 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Actions/Synchronizable.php(32): Picqer\Financials\Moneybird\Connection->get('financial_mutat...', Array) #2 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/cron.php(119): Picqer\Financials\Moneybird\Entities\FinancialMutation->listVersions(Array) #3 /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/cron.php(214): processFinancialMutations(Array, true) #4 {main} {"exception":"[object] (Picqer\\Financials\\Moneybird\\Exceptions\\ApiException(code: 401): Error 401: {\"error\":\"No access to bank\"} at /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Connection.php:496, GuzzleHttp\\Exception\\ClientException(code: 401): Client error: `GET https://moneybird.com/api/v2/999999999999999999/financial_mutations/synchronization.json?filter=period%3A201906..201907%2Cmutation_type%3Adebit` resulted in a `401 Unauthorized` response:\n{\"error\":\"No access to bank\"}\n at /var/www/vhosts/localhost/whmcs.localhost/modules/addons/moneybird/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)"} []

**Comment by ju5t** [comment]
What error are you confirming? The error you have pasted here seems to be raised because you've used incorrect credentials. This is most likely a misconfiguration in your installation. The error you are getting is:

```
Error 401: {"error":"No access to bank"}
```

To be clear, this specific bug this issue addresses only affects the internal update mechanism in WHMCS, all other functionality is unaffected.

**Comment by vertizio** [comment]
Ok, thanks for clarifying. Will check the configuration.

--

sjoerd

:wq

**Comment by ju5t** [comment]
The latest version of WHMCS should resolve this. Closing this issue. Please open a new issue if you see this on the latest version of WHMCS, in that case, there might be something else going on.
