### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DaanVri** [sensson/whmcs-moneybird#7]
![image](https://user-images.githubusercontent.com/53516606/62203077-c8f6ff80-b38a-11e9-8b4f-6cacf5b27401.png)

Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

```
Whoops\Exception\ErrorException: require(): Failed opening required '/home/admin/domains/fronix.nl/private_html/modules/addons/moneybird/vendor/autoload.php' (include_path='.:/usr/local/php72/lib/php') in /home/admin/domains/fronix.nl/private_html/modules/addons/moneybird/moneybird.php:22
Stack trace:
#0 /home/admin/domains/fronix.nl/private_html/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'require(): Fail...', '/home/admin/dom...', 22)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}
```

**Comment by ju5t** [comment]
It's a little difficult to debug this without knowing on which page or during which process this happened. Could you share some more information?

**Comment by ju5t** [comment]
Ah wait, I think I know. Did you follow the instructions in the README? I think you forgot to run `composer install` on your local machine before uploading the files. If that's not an option, you can run it on the server WHMCS runs on, too. Assuming you have shell access that is.

**Comment by DaanVri** [comment]
Hey,

We have it
https://fronix.nl/scr/9hh1BDjHlN.png

**Comment by ju5t** [comment]
Some things aren't matching up.

* The username in your error message is `admin`. In your screenshot it's `Daan`.
* `composer install` is supposed to give you a lot more output.

Are you sure you ran `composer install` in the directory of the module? According to your error message this would be: `home/admin/domains/fronix.nl/private_html/modules/addons/moneybird`.

**Comment by DaanVri** [comment]
Hey Hey,

we have a new error:

> PDOException: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'mod_moneybird_workflow_links' already exists in /home/admin/domains/fronix.nl/private_html/vendor/illuminate/database/Connection.php:441
Stack trace:
#0 /home/admin/domains/fronix.nl/private_html/vendor/illuminate/database/Connection.php(441): PDOStatement->execute(Array)
#1 /home/admin/domains/fronix.nl/private_html/vendor/illuminate/database/Connection.php(706): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'create table `m...', Array)
#2 /home/admin/domains/fronix.nl/private_html/vendor/illuminate/database/Connection.php(669): Illuminate\Database\Connection->runQueryCallback('create table `m...', Array, Object(Closure))
#3 /home/admin/domains/fronix.nl/private_html/vendor/illuminate/database/Connection.php(442): Illuminate\Database\Connection->run('create table `m...', Array, Object(Closure))
#4 /home/admin/domains/fronix.nl/private_html/vendor/illuminate/database/Schema/Blueprint.php(83): Illuminate\Database\Connection->statement('create table `m...')
#5 /home/admin/domains/fronix.nl/private_html/vendor/illuminate/database/Schema/Builder.php(229): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#6 /home/admin/domains/fronix.nl/private_html/vendor/illuminate/database/Schema/Builder.php(148): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#7 /home/admin/domains/fronix.nl/private_html/modules/addons/moneybird/moneybird.php(190): Illuminate\Database\Schema\Builder->create('mod_moneybird_w...', Object(Closure))
#8 /home/admin/domains/fronix.nl/private_html/admin/configaddonmods.php(0): moneybird_upgrade(Array)
#9 {main}
Next Illuminate\Database\QueryException: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'mod_moneybird_workflow_links' already exists (SQL: create table `mod_moneybird_workflow_links` (`whmcs_payment_method` varchar(255) not null, `moneybird_workflow_id` text not null) default character set utf8 collate utf8_unicode_ci) in /home/admin/domains/fronix.nl/private_html/vendor/illuminate/database/Connection.php:713
Stack trace:
#0 /home/admin/domains/fronix.nl/private_html/vendor/illuminate/database/Connection.php(669): Illuminate\Database\Connection->runQueryCallback('create table `m...', Array, Object(Closure))
#1 /home/admin/domains/fronix.nl/private_html/vendor/illuminate/database/Connection.php(442): Illuminate\Database\Connection->run('create table `m...', Array, Object(Closure))
#2 /home/admin/domains/fronix.nl/private_html/vendor/illuminate/database/Schema/Blueprint.php(83): Illuminate\Database\Connection->statement('create table `m...')
#3 /home/admin/domains/fronix.nl/private_html/vendor/illuminate/database/Schema/Builder.php(229): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\MySqlConnection), Object(Illuminate\Database\Schema\Grammars\MySqlGrammar))
#4 /home/admin/domains/fronix.nl/private_html/vendor/illuminate/database/Schema/Builder.php(148): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#5 /home/admin/domains/fronix.nl/private_html/modules/addons/moneybird/moneybird.php(190): Illuminate\Database\Schema\Builder->create('mod_moneybird_w...', Object(Closure))
#6 /home/admin/domains/fronix.nl/private_html/admin/configaddonmods.php(0): moneybird_upgrade(Array)
#7 {main}

**Comment by ju5t** [comment]
Can you share more information in the future about what you have done exactly? Sharing error messages gives an idea but doesn't paint the full picture. It can be extremely difficult to figure out what's wrong.

Either way, you should never see this error message. I did find a small bug that keeps you from activating the module if any of the tables exist already. I do think the code that handles this can be improved, but for now a quick fix has been added to the develop branch.

If you haven't been using the module I would personally drop all mod_moneybird prefixed tables from your database and activate it again. That should 100% solve any issues you are having.

**Comment by DaanVri** [comment]
Hey, I just installed the composer and added the code, but I didn't even get it on the module activation page when activating the module. I therefore cannot reactivate the module.

**Comment by ju5t** [comment]
Have you tried dropping all mod_moneybird tables yet?

**Comment by DaanVri** [comment]
Yes i tried

**Comment by ju5t** [comment]
I'm sorry, but I really can't help you if you don't open up a bit more. It's impossible for me to guess what you have done. Unless you start giving me all the information you can possible think of and explain every step you have taken, I am not going to be able to help you further.

- Are you 100% sure you've used DROP TABLE and not TRUNCATE TABLE?
- What happened when you dropped all tables and you accessed configaddonmods.php?

If you have done anything else I would like to know what. 

- Did you try to activate the addon again and what happened when you did?
- Did you check if all tables were created properly right after you hit the activate button? You should have the following tables mod_moneybird_log, mod_moneybird_ledger_links, mod_moneybird_tax_links, mod_moneybird_invoice_links, mod_moneybird_customer_links, mod_moneybird_workflow_links.
- Did you try deactivating the module first, then dropping all tables and then reactivating again?

**Comment by DaanVri** [comment]
Hello, I can't give a lot of information because I haven't done a lot. I only installed the composer in home/admin/domains/fronix.nl/private_html/modules/addons/moneybird . So after that I added your moneybird module and then on the configaddonmods.php page I got this error. I have activated neits or something I have only installed the composer and then I have only added the module. More no less either.

**Comment by ju5t** [comment]
What do you mean by 'added the module'?

I would:

- Remove the folder /home/admin/domains/fronix.nl/private_html/modules/addons/moneybird
- Drop the database tables mod_moneybird_log, mod_moneybird_ledger_links, mod_moneybird_tax_links, mod_moneybird_invoice_links, mod_moneybird_customer_links, mod_moneybird_workflow_links.
- Download the develop branch: https://github.com/sensson/whmcs-moneybird/archive/develop.zip
- And follow all of the installations steps in the README provided with this module.

If that doesn't work something is wrong with your installation. I'm afraid I can't support you with that. We have open sourced this module because we can't give full support on it and we expect its users to be familiar with PHP and WHMCS. If you aren't that's ok of course, but in that case this module may not be suitable for you.
