### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by biwd** [sensson/whmcs-moneybird#8]
He,

I have this error,
Error: Class 'Picqer\Financials\Moneybird\Connection' not found in 

Is this because i got the wrong connetcion details or is something else wrong?
Use whmcs 7.8.1

**Comment by ju5t** [comment]
WHMCS 7.8 was only released a few days ago. We haven't had the chance to test it yet.

Just to be sure; did you follow the exact steps from the README and did you run `composer install`?

**Comment by biwd** [comment]
no i did not run the composer. I upload the files with ftp en followed the steps by whmcs.

**Comment by ju5t** [comment]
@biwd you have to run `composer install` as the README says. You can't leave out one of the installation steps.

See: https://github.com/sensson/whmcs-moneybird#installation

**Comment by twelvetrains** [comment]
Also for me, there is simply not enough information as exactly how the installation should be done. When I run 'composer install' in SSH on the server, I get the following error:

"Composer could not find a composer.json file in /home/twelve1q"

When i run 'composer install /home/twelve1q/public_html/accounts/modules/addons/moneybird' I also get an error. 

Could the installation information please be updated with the exact instructions? I would really appreciate that. :-)

WHMCS is updated to the most recent stable version: 7.9.1
